In [92]:
import cv2

flags = [i for i in dir(cv2) if i.startswith('COLOR_')]
len(flags)
print(len(flags))
flags[40]

274


'COLOR_BGR2HLS'

In [96]:
import matplotlib.pyplot as plt
import numpy as np


In [97]:
NomeArquivo='MosaicoPouco.png'
#NomeArquivo='MetadeAreaTotal.png'
nemo = cv2.imread(NomeArquivo)
plt.imshow(nemo)

plt.show()

In [98]:
%matplotlib qt
plt.figure(1)
nemo = cv2.cvtColor(nemo, cv2.COLOR_BGR2RGB)
plt.imshow(nemo)
plt.show()


In [99]:
%matplotlib qt
hsv_nemo = cv2.cvtColor(nemo, cv2.COLOR_RGB2HSV)
plt.imshow(hsv_nemo)
plt.show()

In [100]:
from matplotlib.colors import hsv_to_rgb
print(hsv_nemo[2000,2400,:])
#2000,2300
#2000,2400
Terra= (177,80,170)
Terra2=(171,50,134)

#Terra = (1, 190, 200)
#Terra2 = (18, 255, 255)

lo_square = np.full((10, 10, 3), Terra, dtype=np.uint8) / 255.0
ho_square = np.full((10, 10, 3), Terra2, dtype=np.uint8) / 255.0

plt.figure(2)
plt.subplot(1, 2, 1)
plt.imshow(hsv_to_rgb(lo_square))
plt.subplot(1, 2, 2)
plt.imshow(hsv_to_rgb(ho_square))
plt.show()

[171  76 134]


In [101]:
mask = cv2.inRange(hsv_nemo, Terra2, Terra)
print(mask)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [102]:
result = cv2.bitwise_and(nemo, nemo, mask=mask)

In [116]:
plt.figure(4)
plt.subplot(1, 2, 1)
plt.imshow(mask, cmap="gray")
plt.subplot(1, 2, 2)
plt.imshow(result)
plt.show()

C:\Users\Novis\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  
C:\Users\Novis\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  after removing the cwd from sys.path.


In [110]:
result1 = cv2.cvtColor(result, cv2.COLOR_BGR2GRAY)
Filtro=np.asarray(result1)
print(Filtro.shape)

(4179, 8500)


In [115]:
print(np.mean(Filtro[1000:1010,1000:1010]))

0.0
